### ISSUE TITLE
[!issue] 

### ISSUE THREAD

**Issue by ctkqiang** [Santos-Enoque/flutter-groceries-shopping-app#1]
This is nice. Keep me posted for your youtube video <3

**Comment by trinib** [comment]
yea man love your work and dedication..keep it up ..

**Comment by Santos-Enoque** [comment]
> yea man love your work and dedication..keep it up ..

Thank you

**Comment by Santos-Enoque** [comment]
> This is nice. Keep me posted for your youtube video <3

THanks
